// Generated by CoffeeScript 1.7.1
(function() {
  this.Game = (function() {
    function Game() {
      console.log("Game Launched.");
      this.preloader = new Preloader(this);
      this.preloader.setPath("images/game/");
      this.preloader.addImage("test.png", "player");
      this.preloader.preloadImages();
    }

    Game.prototype.preloadDone = function() {
      return console.log("Preloader done.");
    };

    return Game;

  })();

  window.game = new Game();

}).call(this);
